import Head from "next/head";
import { GameBoard } from "~/components/GameBoard";
import { GameStats } from "~/components/GameStats";
import Header from "~/components/Header";
import NoSSR from "~/components/NoSSR";
import { GameProvider } from "~/providers/GameProvider";

function Home() {
  return (
    <>
      <Head>
        <title>QuickTyper</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <GameProvider>
        <main className="flex min-h-screen w-full flex-col items-center justify-start border-r-8  px-24">
          <NoSSR>
            <Header />
            <GameStats />
            <GameBoard />
          </NoSSR>
        </main>
      </GameProvider>
    </>
  );
}

export default function HomePage(props: any) {
  return (
    // <NoSSR>
    <Home />
    // </NoSSR>
  );
}
